config/routes.rb
Jurnalo::Application.routes.draw do
  
  resources :invitations

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "static_pages/home"

  get "static_pages/about"

  get "static_pages/privacy"

  get "static_pages/contact"

  get "static_pages/fb_new"

  get "static_pages/register"

get 'contact', to: 'static_pages#contact', as: 'contact'
get 'privacy', to: 'static_pages#privacy', as: 'privacy'
get 'about', to: 'static_pages#about', as: 'about'
get 'login', to: 'sessions#new', as: 'login'
get 'logout', to: 'sessions#destroy', as: 'logout'
get 'edit', to: 'users#edit', as: 'edit'
get 'register', to: 'static_pages#register', as: 'register'

match '/signup(/:invitation_token)' => 'users#new', as: 'signup'

match 'auth/:provider/callback', to: 'sessions#fb_create'
match 'auth/failure', to: redirect('/')
match 'signout', to: 'sessions#destroy', as: 'signout'

get "/sitemap.:format", to: "authors#sitemap", as: "sitemap"

resources :users do
    member do
      get :following, :followers, :authors
    end
end

resources :posts do
    member do
      get :star, :unstar, :share, :like, :preview
      post :add_comment, :add_message
    end
    collection { post :sort }
end

resources :subscriptions do
    member do
      get :star, :unstar, :subscribe, :unsubscribe
      post :subscribe, :unsubscribe
    end
end

resources :authors do
    member do
      get :similar, :like
    end
end

resources :articles do
    member do
      get  :share, :like, :preview, :call
      post :add_comment, :add_message
    end
    collection { post :sort }
end

resources :filters do
    member do
      post :new
    end
end

resources :static_pages do
    member do
      post :add_message
    end
end

resources :actions do
    member do
      post :add_comment
    end
    collection { post :sort }
end

resources :articles
resources :actions
resources :authors
resources :catchers

resources :filters, only: [:new, :create, :destroy]
resources :posts, only: [:new, :create, :destroy]
resources :sessions
resources :relationships, only: [:new, :create, :destroy]
resources :subscriptions, only: [:new, :create, :destroy]
resources :password_resets

resources :facebook_updates, :only=>[:create, :index]

   root :to => 'static_pages#home'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :authorize, only: [:fb_new]
  before_filter :check_for_canvas, only: [:home]
  def home
    if current_user
      #@starred_actions = current_user.starred_author_action_feed.where("created_at >= :time", {:time => 1.day.ago}).sort_by{|e| -e[:id]}
      #@starred_actions = current_user.starred_author_action_feed.find_all{|i| i.created_at >= 24.hours.ago}.sort_by{|e| -e[:id]}
      #@user_actions = current_user.user_action_feed
      #@unique_user_actions =[]
      #@unique_user_actions += Array.wrap(@user_actions.first)
      #@user_actions.each do |a|
      #  @unique_user_actions += Array.wrap(a) if @unique_user_actions.find_all{|i| i.article_id == a.article_id}==[]
      #end

      # @actions = (@unique_user_actions + current_user.author_action_feed - @starred_actions).sort_by{|e| -e[:id]}
      #@starred_section_actions = (@starred_actions + current_user.friends_action_feed).find_all{|i| i.created_at >= 24.hours.ago}.sort_by{|e| -e[:id]}
      @author_actions = current_user.author_action_feed.find_all{|i| i.created_at >= 24.hours.ago}
      @actions =  (current_user.friends_action_feed + @author_actions).sort_by{|e| -e[:id]}
     
      @popular_actions, @popular_authors = Action.latest_from_top_authors

      @popular_actions -= @actions 
      

      #@user_actions=current_user.user_action_feed
      
      if @actions.empty?
        flash.now[:notice] = "Follow your favorite econ bloggers to always see their posts on top!" unless flash[:notice]
       #elsif current_user.starred_subscriptions.empty?
       # flash.now[:notice] = "Star your favorite columnists by clicking the star buttons on the right." unless flash[:notice]
     #   elsif @utopics.empty?
     #   flash[:notice] = "Click 'select topic!' underneath any headline to categorize a post."
     #   end
      end


        #@starred_actions = Kaminari.paginate_array(@starred_actions).page(params[:page]).per(50)
        @actions = Kaminari.paginate_array(@actions).page(params[:page]).per(50)
        @popular_actions = Kaminari.paginate_array(@popular_actions).page(params[:page]).per(50)
        #  @user_actions = Kaminari.paginate_array(@user_actions).page(params[:page]).per(50)

        @recommended, @popular = current_user.recommended
          

    else
      #flash.now[:notice] = "Star your favorite economists to always see their posts on top!" unless flash[:notice]
      @actions, @popular = Action.latest_from_top_authors
      @actions = Kaminari.paginate_array(@actions).page(params[:page]).per(50)
      
    end

 
  end

  def register
  end

  def fb_new
    redirect_to root_url

  end

  def privacy
  end
  
  def terms
  end

  def about
  end

  def add_message
    @message = params[:message]
    @user = current_user
    unless @message ==nil
       UserMailer.delay.send_message(@message, @user)
       redirect_to root_url, :notice => "Message submitted."
    end
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div class="row">
  <div class = "span7">
  	<div class ="upper_section">
<h3>About</h3>

<br><%= link_to "EconBloggers.com", root_path %> is made for people who can't stop reading econ blogs.

<br><br>
<b>By which criteria are econ bloggers included in this site?</b>
<br><br>
1.They publish articles/blog posts in popular news publications or blogs.<br>
2.They have an academic or professional background in economics. 
<br><br>
<b>How are the '<%= link_to "Top Econ Bloggers", authors_path %>' determined?</b>
<br><br>
They are simply <%= link_to "ranked", authors_path %> by their number of followers on <%= link_to "EconBloggers.com", root_path %>.
</div>
</div>
</div>

app/views/static_pages/contact.html.erb
<div class="row">
	<div class = "span8">
		<div class ="upper_section">



  	<h3>
Contact EconBloggers</h3>
<br><br>
<%= form_tag(:controller => "static_pages", :action => 'add_message', :id => 1) do %>
                        <div id ="comment_image"> <%= link_to (image_tag current_user.picture, :width => "26"), current_user if current_user %></div>
                        <div id ="comment_field"><%= text_field_tag :message, nil, :placeholder => 'Write a message to EconBloggers...'%> </div>
                        <div class="actions"><%= submit_tag "Send", class: "btn btn-primary" %></div>
                  <% end %>
            
</div>
</div>
</div>

app/views/static_pages/home.html.erb
<% content_for :title, "EconBloggers - All econ bloggers on one page!" %>
<% if current_user %>
      
      <%= render 'shared/feed' %>
 
    


<% else %>

  <%= render 'shared/home_feed' %>

<% end %> 

app/views/static_pages/privacy.html.erb
<div class="row">
  <div class = "span7">
  	<div class ="upper_section">
<h3>Privacy policy</h3>

<br>1.	When you 'follow' an econ blogger or 'like' an article on EconBloggers.com these actions will be visible on your Facebook timeline. 
<br><br>3.	The visibility on EconBloggers.com of 'comment' and 'like' actions on articles and actions posted on EconBloggers.com and EconBloggers.com related actions on Facebook is entirely based on your corresponding privacy settings on Facebook.
 
<br><br>4.	EconBloggers.com collects personal information when you register or when you provide such information voluntarily.

<br><br>5.	We use cookies and other technologies to find out how you use EconBloggers.com.

<br><br>6.	EconBloggers.com accesses information automatically when you visit our site. This information includes URL, IP-address, browser-type, language as well as date and time of your visit.

<br><br>7.	We don't pass on personal information to any third party beyond other EconBloggers.com users as specified above without your explicit approval.

<br><br>8.	Only summarized de-personalized information is provided to third parties.

<br><br>9.	Personal information is used for providing services requested by the user including services with personalized content.

<br><br>10.	Additionally, we use your personal information for internal research in order to improve your online experience as well as our technologies and services.
</div>
</div>
</div>

app/views/static_pages/register.html.erb
<div class="center hero-unit">
     <h2>
      Login for your personalized newsfeed!
    </h2>
    <%= link_to "Signup", signup_path, id: "sign_in", 
                                class: "btn btn-large btn-info" %>

<%= link_to "Login", login_path, id: "sign_in", 
                                class: "btn btn-large btn-info" %>
    <%= link_to "Login via Facebook!", "/auth/facebook", id: "sign_in", 
                                class: "btn btn-large btn-primary" %>

  </div>