config/routes.rb
Jurnalo::Application.routes.draw do
  
  resources :invitations

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "static_pages/home"

  get "static_pages/about"

  get "static_pages/privacy"

  get "static_pages/contact"

  get "static_pages/fb_new"

  get "static_pages/register"

get 'contact', to: 'static_pages#contact', as: 'contact'
get 'privacy', to: 'static_pages#privacy', as: 'privacy'
get 'about', to: 'static_pages#about', as: 'about'
get 'login', to: 'sessions#new', as: 'login'
get 'logout', to: 'sessions#destroy', as: 'logout'
get 'edit', to: 'users#edit', as: 'edit'
get 'register', to: 'static_pages#register', as: 'register'

match '/signup(/:invitation_token)' => 'users#new', as: 'signup'

match 'auth/:provider/callback', to: 'sessions#fb_create'
match 'auth/failure', to: redirect('/')
match 'signout', to: 'sessions#destroy', as: 'signout'

get "/sitemap.:format", to: "authors#sitemap", as: "sitemap"

resources :users do
    member do
      get :following, :followers, :authors
    end
end

resources :posts do
    member do
      get :star, :unstar, :share, :like, :preview
      post :add_comment, :add_message
    end
    collection { post :sort }
end

resources :subscriptions do
    member do
      get :star, :unstar, :subscribe, :unsubscribe
      post :subscribe, :unsubscribe
    end
end

resources :authors do
    member do
      get :similar, :like
    end
end

resources :articles do
    member do
      get  :share, :like, :preview, :call
      post :add_comment, :add_message
    end
    collection { post :sort }
end

resources :filters do
    member do
      post :new
    end
end

resources :static_pages do
    member do
      post :add_message
    end
end

resources :actions do
    member do
      post :add_comment
    end
    collection { post :sort }
end

resources :articles
resources :actions
resources :authors
resources :catchers

resources :filters, only: [:new, :create, :destroy]
resources :posts, only: [:new, :create, :destroy]
resources :sessions
resources :relationships, only: [:new, :create, :destroy]
resources :subscriptions, only: [:new, :create, :destroy]
resources :password_resets

resources :facebook_updates, :only=>[:create, :index]

   root :to => 'static_pages#home'

end

app/models/article.rb
class Article < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :feed
  belongs_to :catcher
  default_scope order: 'articles.created_at DESC'
  after_create :publish_action
  has_many :likes

  def to_param
  "#{id}-#{title.downcase.gsub(/[^a-zA-Z0-9]+/, '-').gsub(/-{2,}/, '-').gsub(/^-|-$/, '')}" if title
  end


  #define_index do
  #  indexes title
  #  indexes catcher.author.name, :as => :author
  #  has created_at
  #end



  def publish_action
  	a=Action.new
  	a.publish_article(self)
  end

  #def self.search(search)
#	  if search
#	    where 'title LIKE ?', "%#{search}%"
#	  else
#	    scoped
#	  end
#  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_filter :authorize, only: [:like]


	def like
	    
	    @article = Article.find(params[:id])
	    like = Like.new
	      like.user_id = current_user.id
	      like.article_id = @article.id
	    like.save
	    current_user.like_article_action(like)

	    #a=current_user.facebook.get_connections("me","og.likes")
	    #s=a.select {|f| f["data"]["object"]["url"] == post_url(@post)}
	    #unless s.empty?
	    #  current_user.facebook.delete_object(s.first["id"])
	    #end
	    #current_user.facebook.put_connections("me", "og.likes", object: post_url(@post))
	    
	    current_user.delay.fb_article_like(article_url(@article), @article)
	    
	    #LikeMailer.delay.like_it(@post, current_user)
	    #current_user.facebook.put_like(@post.fbaction_id)
	    redirect_to :back, :notice => "Article has been liked."
	    #redirect_back_or root_url#, :notice => "Article has been liked."
	end


	def show
		@article = Article.find(params[:id])
		@author = @article.catcher.author
		@action = Array.wrap(@article.catcher.author.actions.find_by_article_id(params[:id]))
		@actions = @article.catcher.author.actions - @action
		@actions = Kaminari.paginate_array(@actions).page(params[:page]).per(50)

		if current_user
			@friends = current_user.followed_users
			@subscribed_friends = @friends.find_all{|i| i.subscribed?(@author)}.first(10)
		end
		@all_authors =[]
		@size = @author.users.size
		@author.users.each do |u|
			@all_authors += (u.authors - Array.wrap(@author))
		end

		@author_hash = @all_authors.inject(Hash.new(0)) { |h,n| h[n] += 1; h }
		@author_hash = @author_hash.sort_by {|author, count| -count}
		@ranked_authors = @author_hash.to_a
		@recommended = @ranked_authors.first(3)

		#flash.now[:notice] = "Follow your favorite columnists and get all their articles wherever they're published!" unless current_user


	end	

	def comment
		@article = Article.find(params[:id])
		@author = @article.catcher.author
		render :action => :show, :layout => false
	end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<%= link_to article.title, article.url %> - <%= link_to article.catcher.author.name, author_path(article.catcher.author)  if article.catcher%> - <%= time_ago_in_words(article.created_at) %> ago <br>
<%= link_to 'like', :controller => "articles", :action => "like", :id => article.id %><br><br>

app/views/articles/comment.html.erb
      <style>
      @import "bootstrap";
      @import "bootstrap-responsive";
      ul#bar{ clear:both; padding:0; margin:0; }
      ul#bar li{ float:left; list-style:none; list-style-position:inside; font-size:110%;}
      ul#bar li.story{ padding-left: 40px; }
      ul#bar li.nopadding{ padding: 0; }
      ul#bar li.author{ padding-left: 40px; padding-right: 20px; }
      ul#bar li.stories{ max-width: 280px; width: 280px; *width: 325px;}
      ul#bar li span.heading{ font-family:Arial,Helvetica,sans-serif; font-size:100%; display:block; padding-bottom:5px; font-weight:bold; }
      ul#bar li span.stories { display:block; padding-top:4px; padding-right:5px;}
      ul#bar li a,a:visited{ color:#333333; text-decoration:none; font-family:Arial,Helvetica,sans-serif;}
      ul#bar li.story a,a:visited{ font-family:Georgia,"Times New Roman",Times,serif; }
    ul#bar li.story a:hover{ color:#0000b6; text-decoration: underline; }
      ul#bar li span.arial a,a:visited{ font-family: Arial,Helvetica,sans-serif; }
      ul#bar li.right{ float:right; }
      ul#bar li a.more{ color:#333333; font-family:Arial,Helvetica,sans-serif; padding-top:5px; font-size:100%; display:inline-block;}
    ul#bar li a.this_story{ color:#333333; font-family:Arial,Helvetica,sans-serif; padding-top:0px; font-size:100%; display:inline-block;}
      ul#bar li .inline { display:inline-block; }
      ul#bar li .bold{ font-weight:bold }
      ul#bar li span.grey a { color:#999999; }
      #details{float:left;margin-top:10px}
      #details p{padding:0;margin:0 0 2px}
      img{border:none;padding-top:4px;}
      #outer-separator{clear:both;width:100%;border-top: 7px solid #3B5998;margin:10px 0 2;padding:0;font-size:1px;overflow:hidden}
      #separator{background:#3B5998;height:2px}
      </style>

  <table height="100%" cellspacing="0" cellpadding="0" width="100%">
      <tr style="height:1%">
        <td style="padding-left:10px; padding-top:5px">
          <ul id="bar">
            <li>
               &laquo; <%= link_to('back', :back ) %>
              </li>  
              <li class="author">
               <%= link_to @article.catcher.author.name, @article.catcher.author %>

    
              </li>  
               <li>
                       <div id = "follow_button">
<%= render 'authors/subscribe_form' %></div>
</li>

          </ul>
        </td>
      </tr>
      <tr>
        <td>
          <div id="outer-separator"></div>
          <iframe scrolling="auto" id="rf" src="<%= @article.url -%>" frameborder="0" allowtransparency="true" style="width:100%;height:100%"></iframe>
        </td>
      </tr>
    </table>
    <script>var a = document.getElementById('rf');a && a.contentWindow && a.contentWindow.focus();</script>

</body>
</html>

app/views/articles/index.html.erb
<%= form_tag articles_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :q, nil, :placeholder => 'Search articles...'%>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<%= render @authors%>


       <% if @actions.any? %>

      
         <ol class="profile_microposts">
          <%= render @actions %>
          </ol>
          <br>
          <%= paginate @actions %>
  
        <%end%>

app/views/articles/show.html.erb
<% content_for :head do %>
  <%= tag :meta, property: "fb:app_id", content: ENV['FACEBOOK_APP_ID'] %>
  <%= tag :meta, property: "og:site_name", content: @article.feed.source.name %>
  <%= tag :meta, property: "og:type", content: "article" %>
  <%= tag :meta, property: "article:published_time", content: @article.created_at %>
  <%= tag :meta, property: "article:author", content: author_url(@article.catcher.author) %>
  <%= tag :meta, property: "og:description", content: "by " + @article.catcher.author.name + " on " +  @article.feed.source.name + " found using EconBloggers.com" %>
  <%= tag :meta, property: "og:title", content: @article.title %>
  <%= tag :meta, property: "og:url", content: article_url(@article) %>
  <%= tag :meta, property: "og:image", content: request.protocol + request.host + image_path("newspaper_article.jpeg") %>
  
<% end %>
<% content_for :title, @article.title + " - " %>
<div class="row">
  <div class = "span6">
    <br>
    <ol class="microposts">
      
      <div id ="item_text">

    
      <span class = "user"><%= link_to @article.catcher.author.name, @article.catcher.author %>&nbsp;&nbsp;</span>
       <div id = "follow_button">
<%= render 'authors/subscribe_form' %></div>
      </div>
      <br>

      <div id="<%= @article.id %>">  
      <div id ="item_text">

          <span class="content"><b><%= link_to @article.title, @article.url %></b></span>
       

          

           <span class="article_timestamp"> 

        <!--% if @post.fbaction_id %-->

<%if @article.likes && @article.likes.count > 0  %> 
                <%= link_to 'like', :controller => "articles", :action => "like", :id => @article.id %> (<%=  @article.likes.count.to_s %>) · 
            <%else%>
                 <%= link_to 'like', :controller => "articles", :action => "like", :id => @article.id %> · 
            <%end%>

              <script>


                // assume we are already logged in

          function sendMessage() {
                FB.ui({
                    method: 'send',
                    name: '<%= @article.title%>' ,
                    link: '<%= @article.url%>',
                    })}
           </script>
            <%= link_to_function "send", "sendMessage(); return false;" %> · 
            
              <%= time_ago_in_words(@article.created_at) %> ago   

        </span>
     
          
             
  </span>
        <br><br> 
      	</div>

       
      </div>



     
      
    </ol>
    <br>
    <div class ="upper_section">
      <div class="fb-comments" data-href="<%= article_url(@article)%>" data-num-posts="2"></div>
      <% if @actions.any? %>
      <br><br>
        <span class = "user">More posts by <%= link_to (@article.catcher.author.name).html_safe , @article.catcher.author , title: @article.catcher.author.name, "data-content" => "#{popover_link (@article.catcher.author)}", rel: 'popover', "trigger"=>"hover", "data-placement"=>"right" %></span>
    </div>
        
         <ol class="microposts">
          <%= render @actions %>
          </ol>
          <br>
          <%= paginate @actions %>

        <%end%>
  </div>
      <div class="span2">

        <% if @subscribed_friends && @subscribed_friends.any? %>
        <span class = "user">
        Friends subscribed to <%= link_to (@article.catcher.author.name).html_safe , @article.catcher.author , title: @article.catcher.author.name, "data-content" => "#{popover_link (@article.catcher.author)}", rel: 'popover', "trigger"=>"hover", "data-placement"=>"right" %>  </span>

      
         <ol class="profile_microposts">
          <%= render @subscribed_friends %>
          </ol>
          <br>
      
<%end%>

<% if @recommended.any? %>
<br>
      
        Subscribers of <%= @author.name %> also subscribe to

         <ol class="profile_microposts">
            <% @recommended.each do |r| %>
          <%=    render r[0] %>
          <%end%>
          </ol>
          <br>
          <span class="timestamp">
          <%= link_to raw('<i class="icon-plus"></i> ') + "more similar authors..", :controller => "authors", :action => "similar", :id => @article.catcher.author.id %>
        </span>
          

<%end%>



</div>
  <br>
</div>