config/routes.rb
Jurnalo::Application.routes.draw do
  
  resources :invitations

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "static_pages/home"

  get "static_pages/about"

  get "static_pages/privacy"

  get "static_pages/contact"

  get "static_pages/fb_new"

  get "static_pages/register"

get 'contact', to: 'static_pages#contact', as: 'contact'
get 'privacy', to: 'static_pages#privacy', as: 'privacy'
get 'about', to: 'static_pages#about', as: 'about'
get 'login', to: 'sessions#new', as: 'login'
get 'logout', to: 'sessions#destroy', as: 'logout'
get 'edit', to: 'users#edit', as: 'edit'
get 'register', to: 'static_pages#register', as: 'register'

match '/signup(/:invitation_token)' => 'users#new', as: 'signup'

match 'auth/:provider/callback', to: 'sessions#fb_create'
match 'auth/failure', to: redirect('/')
match 'signout', to: 'sessions#destroy', as: 'signout'

get "/sitemap.:format", to: "authors#sitemap", as: "sitemap"

resources :users do
    member do
      get :following, :followers, :authors
    end
end

resources :posts do
    member do
      get :star, :unstar, :share, :like, :preview
      post :add_comment, :add_message
    end
    collection { post :sort }
end

resources :subscriptions do
    member do
      get :star, :unstar, :subscribe, :unsubscribe
      post :subscribe, :unsubscribe
    end
end

resources :authors do
    member do
      get :similar, :like
    end
end

resources :articles do
    member do
      get  :share, :like, :preview, :call
      post :add_comment, :add_message
    end
    collection { post :sort }
end

resources :filters do
    member do
      post :new
    end
end

resources :static_pages do
    member do
      post :add_message
    end
end

resources :actions do
    member do
      post :add_comment
    end
    collection { post :sort }
end

resources :articles
resources :actions
resources :authors
resources :catchers

resources :filters, only: [:new, :create, :destroy]
resources :posts, only: [:new, :create, :destroy]
resources :sessions
resources :relationships, only: [:new, :create, :destroy]
resources :subscriptions, only: [:new, :create, :destroy]
resources :password_resets

resources :facebook_updates, :only=>[:create, :index]

   root :to => 'static_pages#home'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<div class = "row">



<div class = "span8">

	<% if @actions.any? %>
	<div id = "favorite_posts">
	        
	   Your Newsfeed
	  <ol class="microposts">
	<%= render @actions %>
	</ol>
	</div>
	<br>
	<%end%>
	<% if @popular_actions.any? %>
	<div id = "latest_posts">
		Latest By Other Top Econ Bloggers
	  <ol class="microposts">
	<%= render @popular_actions %>
	</ol>
	</div>
	 <br> 
	<% end %>
	<br>
	  <%= paginate @popular_actions %>

</div>


</div>

app/views/shared/_feed_item.html.erb
<% unless feed_item.hidden? %> 
	<li id="<%= feed_item.id %>">
		<div id ="user_image">
			<%= link_to (image_tag feed_item.user.picture, :width => "25"), feed_item.user  %> 
		</div> 
		<div id ="item_text">
	 		<span class = "user"><%= link_to feed_item.user.name, feed_item.user %> <% unless feed_item.via == nil %> via <%= link_to feed_item.via.name, feed_item.via %> <%end%></span>
	 		

			<br>
	 
			  <span class="content"><%= link_to feed_item.headline, feed_item.url %><br>
			 <% if feed_item.author %>  by <%= feed_item.author %><br><%end%>
			  <%= truncate(feed_item.description, :length => 100, :omission =>"...", :separator => ' ') %> </span>
			    


			<span class="timestamp"> 
				<% if feed_item.user == current_user %> 
					
				 	<% if feed_item.topic %><span class="editable_topic"><i class="icon-cog"></i><% selected_topic = feed_item.topic.name %> <%else%><i class="icon-list"></i><span class ="edit_topic">

				 	<% selected_topic = "select topic!" %> <%end%>
					 <%= best_in_place feed_item, :topic_id, type: :select, collection: Topic::list_topic_options, :nil => "#{selected_topic}"%></span> · 
				<%else%>
			 		<%= feed_item.topic.name + " · " unless feed_item.topic == nil  %> 
			 	<%end%>
			 	 
			 	 <!--% if feed_item.fbaction_id %-->
				 	 <%if feed_item.likes_count && feed_item.likes_count > 0  %>	
				 	  <%= link_to 'like', :controller => "posts", :action => "like", :id => feed_item.id %> (<%=  feed_item.likes_count.to_s %>) · 
				 	  <%else%>
				 	   <%= link_to 'like', :controller => "posts", :action => "like", :id => feed_item.id %> · 
				 	 <%end%>
				  <!--%end%-->  
				 	<%if feed_item.comments && feed_item.comments.count > 0  %>	
				 	<%= link_to "comments (" + feed_item.comments.count.to_s + ")" , feed_item %> · 
				 	<%else%>
	   				<%= link_to "comment", feed_item %> · 
	   				<%end%>
	   
	    

				<% if current_user != feed_item.user %> 
			<%= link_to "repost", "data-target" => "#preview", "data-toggle" => "modal", "href" => "remote.html", :controller => "posts", :action => "preview", :id => feed_item.id %> · 
	    <%end%><%= time_ago_in_words(feed_item.created_at) %> ago 
	    <% if current_user == feed_item.user %> 
			  		&nbsp;<%= link_to "x", feed_item, method: :delete,
			                                     data: { confirm: "You sure?" },
			                                     title: feed_item.url %> <%end%>
	 	
			</span>
			
		</div> 	 
	</li>
<%end%>

app/views/shared/_home_feed.html.erb
<div class = "row">


<div class = "span8">

	<% if @actions.any? %>
	<div id = "latest_posts">
		<b>Latest By <%= link_to "Top Econ Bloggers", authors_path %></b>
	  <ol class="microposts">
	<%= render @actions %>
	</ol>
	</div>
	 <br> 
	<% end %>
	<br>
	  <%= paginate @actions %>

</div>


</div>

app/views/shared/_post_form.html.erb
<div class="modal hide" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3>Post a link</h3>
	</div>
	
		<div class="modal-body">
			<%= simple_form_for build_a_post do |f| %>

			  <%= render 'shared/error_messages', object: f.object %>
			  <div id="form_image">
			  <%= link_to (image_tag current_user.picture, :width => "26"), current_user  %>
			</div>
			  <div id="post_box">
			    <%= f.text_field :url, placeholder: "Enter a url..." %>
			  </div>
			 <div id="select_box">
			  <%= f.association :topic, :prompt => "topic", :label => false %>
			</div>
			<div id="privacy_checkboxes" rel="tooltip" title="show this post on my Facebook profile" data-placement="right">
			 <%= f.input :facebook, :label => "share on Facebook", :input_html => { :checked => true },:wrapper => :inline_checkbox %>  </div>
			 <div id="privacy_checkboxes" rel="tooltip" title="email my followers on EconBloggers" data-placement="right">
			 <%= f.input :email, :label => "notify my followers", :input_html => { :checked => true },:wrapper => :inline_checkbox %></div>
			 <div id="privacy_checkboxes" rel="tooltip" title="make this post visible to all EconBloggers users" data-placement="right">
			 <%= f.input :public, :label => "make it public", :input_html => { :checked => true }, :wrapper => :inline_checkbox %></div>
			
		</div>
		<div class="modal-footer">

			<div id="button_box">
			  <%= f.submit "Post", class: "btn btn-medium btn-primary btn-posting" %>
			</div>
		<% end %>
		
		</div>
	
</div>

app/views/shared/_preview.html.erb
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3>Repost (preview)</h3>
	</div>
	
		<div class="modal-body">
			

			  
			<div id="<%= @new_post.id %>">  
      <div id ="post_image"><%= link_to (image_tag @new_post.picture, :width => "50"), @post.url if @post.picture != nil  %></div>

      <div id ="item_text">

          <span class="content"><b><%= link_to @new_post.headline, @post.url %></b></span>
          <% if @new_post.author %>  <%= @new_post.author %><%end%>
            <span class="content"><%= truncate(@new_post.description, :length => 100, :omission =>"...", :separator => ' ') %>  
            	</span>
            </div>
        </div>

		<%= simple_form_for current_user.posts.build do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		<%= f.hidden_field :url, :value =>  @new_post.url %>
		<%= f.hidden_field :headline, :value =>  @new_post.headline %>
		<%= f.hidden_field :author, :value =>  @new_post.author %>
		<%= f.hidden_field :description, :value =>  @new_post.description %>
		<%= f.hidden_field :topic_id, :value =>  @new_post.topic_id %>
		<%= f.hidden_field :via_id, :value =>  @new_post.via_id %>
		<%= f.hidden_field :picture, :value =>  @new_post.picture %>
		<br>
		<div id="privacy_checkboxes" rel="tooltip" title="show this post on my Facebook profile" data-placement="right">
			 <%= f.input :facebook, :label => "share on Facebook", :input_html => { :checked => true },:wrapper => :inline_checkbox %>  </div>
			 <div id="privacy_checkboxes" rel="tooltip" title="email my followers on EconBloggers" data-placement="right">
			 <%= f.input :email, :label => "notify my followers", :input_html => { :checked => true },:wrapper => :inline_checkbox %></div>
			 <div id="privacy_checkboxes" rel="tooltip" title="make this post visible to all EconBloggers users" data-placement="right">
			 <%= f.input :public, :label => "make it public", :input_html => { :checked => true }, :wrapper => :inline_checkbox %></div>
			
		</div>
		<div class="modal-footer">

			<div id="button_box">
			  <%= f.submit "Repost this link", class: "btn btn-medium btn-primary btn-posting" %>
			  <%= link_to "Cancel", :back, :class => 'btn' %>
			</div>
		<% end %>
		
		</div>

	

app/views/shared/_stats.html.erb
<br>
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= authors_user_path(@user) %>">
    <strong id="authors" class="stat">
      <%= @user.authors.count %>
    </strong>
    econ bloggers
  </a>
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    followed users
  </a>
    <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    following users
  </a>
  <% if @user == current_user %>
   <a href="<%= edit_user_path(current_user) %>">
    <strong id="authors" class="stat">
     
    </strong>
    <br> settings
  </a>
<%end%>
</div>
<br>

app/views/shared/_topic_menu.html.erb
<div class ="hidden-phone">
      <ul class="nav nav-tabs">
       <% if params[:topic] == nil %> 
       <li class="active"> 
       <%else%>
       <li>
       <%end%>
        <%= link_to "All", :topic => nil %>
      </li>

      <% @topics.each do |topic| %>

       <% if params[:topic] == topic.id.to_s %> 
       <li class="active"> 
       <%else%>
       <li>
        <%end%>
       
       <%= link_to topic.name, :topic => topic.id %> </li>
       
       <%end%>
      
  </ul>
</div>

app/views/shared/_user_info.html.erb
<h1>
<%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.posts.count, "post") %>
</span>

app/views/shared/_utopic_menu.html.erb
<div class ="hidden-phone">
  
      <ul class="nav nav-tabs">
        
       <% if params[:topic] == nil %> 
       <li class="active"> 
       <%else%>
       <li>
       <%end%>
        <%= link_to "All", :topic => nil %>
      </li>

      <% @utopics.each do |utopic| %>
      <% if utopic.topic_id != 0 %>
       <% if params[:topic] == utopic.topic.id.to_s %> 
       <li class="active"> 
       <%else%>
       <li>
        <%end%>

       
       <%= link_to utopic.topic.name, :topic => utopic.topic.id %> </li>

       <%end%>
       <%end%>
      
  </ul>
  
</div>

app/views/shared/waste.html.erb
<h3>PostsPofsts <%if @current_topic != nil %> on <%= @current_topic.name %> <%end%> (<%= @posts.count %>) </h3>